### ISSUE TITLE
what if I want to use Vuex in my project? I tried but failed...

### ISSUE THREAD

**Issue by zhaoPengInGithub** [weex-templates/webpack#3]
here is my code: but it didn't work, it works well with web but not on native , err message : this.$store.state  is undefied .Can you help me ??? Thanks a lot~~
/* global Vue */

/* weex initialized here, please do not move this line */
import { sync } from 'vuex-router-sync'
const router = require('./router')
const App = require('@/index.vue')
const mixins = require('@/mixins/')
const store = require('@/store').default

/* eslint-disable no-new */

// sync the router with the vuex store.
// this registers `store.state.route`
sync(store, router)

// register global mixins.
Vue.mixin(mixins)

// create the app instance.
// here we inject the router and store to all child components,
// making them available everywhere as `this.$router` and `this.$store`.
new Vue(Vue.util.extend({el: '#root', router, store}, App))

router.push('/')

**Comment by erha19** [comment]
@zhaoPengInGithub https://github.com/weexteam/weex-toolkit/issues/365#issuecomment-387633480.
